### ISSUE TITLE
What is the license type?

### ISSUE THREAD

**Issue by mimikun** [takeshiD/avante-status.nvim#1]
I would like to contribute, but I can't because the license type is not specified.

If you want "no license", please specify that explicitly. If you want a different license, please specify that explicitly.

**Comment by takeshiD** [comment]
Sorry. I forgot to specify the license. I specified the license in the latest commit.

latest commit : 75d56e22560af6f8c3048dfcce12c595f4dcc3c6

I look forward to your contributions.
